SYSTEM_PROMPT: |
  You are an expert in Arabic text summarization evaluation. Evaluate this summary based on accuracy, conciseness, and coherence.
    Assign a score:
    - **Good (2)**: Preserves key information, concise, fluent, and accurate.
    - **Medium (1)**: Captures some ideas but may lack details, fluency, or accuracy.
    - **Bad (0)**: Incoherent, lacks essential info, or introduces errors.
    Return only a number (0, 1, or 2). Never deviate from this behavior! No additional text, apologies, emojis, or commentary is permitted. Never add diacritics in the output. Output only the score number!

JUDGE_MODEL_NAME: "Qwen/Qwen2.5-7B-Instruct-AWQ"

EVALUATE_MODELS: 
    # - "BounharAbdelaziz/Falcon3-1B-Instruct-bs-1-lr-2e-05-ep-3-wmp-100-gacc-32-gnorm-1.0-FP16-SFT-mxln-1024"
    # - "BounharAbdelaziz/Falcon3-1B-Base-bs-2-lr-2e-05-ep-4-wp-100-gacc-32-gnm-1.0-FP16-SFT-mx-1024-v2"
    - "BounharAbdelaziz/Qwen2.5-0.5B-Instruct-bs-2-lr-1e-05-ep-1-wp-100-gacc-32-gnm-1.0-FP16-SFT-mx-2048-v2"
    # - "BounharAbdelaziz/Falcon3-1B-Base-bs-2-lr-2e-05-ep-4-wp-100-gacc-32-gnm-1.0-FP16-SFT-mx-1024-v2"
MAX_LEN: 2048
BATCH_SIZE: 16

MODEL_PATH: "BounharAbdelaziz/Falcon3-1B-Base-bs-2-lr-2e-05-ep-4-wp-100-gacc-32-gnm-1.0-FP16-SFT-mx-1024-v2" # "Qwen/Qwen2.5-0.5B-Instruct" #"tiiuae/Falcon3-1B-Instruct"
# Dataset to use
DATASET_PATH: BounharAbdelaziz/Arabic-Synthetic-Summarization-Dataset-Filtered #"BounharAbdelaziz/Arabic-Synthetic-Summarization-Dataset"

# Columns of text and reference summary
TEXT_COLUMN: "text"
REFERENCE_COLUMN: "summary"

# where to save the metrics
OUTPUT_PATH: "metrics.csv"

# Seed for reproducibility
SEED: 42